# Generated by Django 3.0.3 on 2020-03-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adtaa', '0006_auto_20200307_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcourse',
            name='scheduleNumber',
            field=models.IntegerField(default=0),
        ),
    ]
